Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 512
      Handler: helloworld.App
      CodeUri: /Users/amsha/Desktop/Courses and Resources/Lambda/Hello World lambda/HelloWorldFunction
      Runtime: java17
      Architectures:
        - arm64